### ISSUE TITLE
SyntaxError with strict mode

### ISSUE THREAD

**Issue by MrHalfman** [dthree/vantage#29]
Hi, I'm trying to use vantage but when I require the lib in my code I get this error : 
```
[...]/node_modules/vantage/lib/vantage.js:766
    function parseArgsByType(arg, cmdArg) {
    ^^^^^^^^
SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/halfman/beam.io/server.js:6:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

Here is my environment :
```
$ uname -srvo
Linux 3.19.0-25-generic #26-Ubuntu SMP Fri Jul 24 21:17:31 UTC 2015 GNU/Linux

$ npm --versions
{ 'beam.io': '0.0.0',
  npm: '2.11.3',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.7',
  openssl: '1.0.1p',
  uv: '1.6.1',
  v8: '3.28.71.19',
  zlib: '1.2.8' }
```

*Note* : I also get the same error if I type "vantage" in console.

Thanks for your help.

**Comment by dthree** [comment]
Whoops - created this problem yesterday and right away pushed a fix to this in Github but didn't push to NPM. 

NPM `v1.3.2` has this amended. Thanks for letting me know.

**Comment by MrHalfman** [comment]
Thanks :smile:

**Comment by dthree** [comment]
Yeah no problem.

:rocket:
