### ISSUE TITLE
SyntaxError: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by clonq** [dthree/vantage#31]
vantage 1.3.6
running app from .bin I get:

node_modules/vantage/lib/util.js:62
    let arrClone = _.clone(arr);
    ^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

any hints?

**Comment by dthree** [comment]
Sorry about that. I've been writing ES2015 in another module and made a quick fix on Vantage, and took the es6 with  me (let). haha.

I just pushed the fix. You should be good now.
