### ISSUE TITLE
Can't execute tour after 1.4.0 release

### ISSUE THREAD

**Issue by zmarouf** [dthree/vantage#37]
On OSX with node 0.12.7 and vantage 1.5.0 I get this:
```
$ npm install -g vantage
    $ vantage tour
tour~$

/Users/zmarouf/.nvm/versions/node/v0.12.7/lib/node_modules/vantage/node_modules/vorpal/lib/ui.js:236
    this._activePrompt.clean();
                       ^
TypeError: undefined is not a function
    at Object.ui.pause (/Users/zmarouf/.nvm/versions/node/v0.12.7/lib/node_modules/vantage/node_modules/vorpal/lib/ui.js:236:24)
    at Object.ui.log (/Users/zmarouf/.nvm/versions/node/v0.12.7/lib/node_modules/vantage/node_modules/vorpal/lib/ui.js:335:23)
    at Vorpal.vorpal.log (/Users/zmarouf/.nvm/versions/node/v0.12.7/lib/node_modules/vantage/node_modules/vorpal/lib/vorpal.js:274:15)
    at Function.Logger.log.br (/Users/zmarouf/.nvm/versions/node/v0.12.7/lib/node_modules/vantage/lib/logger.js:136:12)
    at Object.steps.step1 (/Users/zmarouf/.nvm/versions/node/v0.12.7/lib/node_modules/vantage/examples/tour/tour.js:67:9)
    at Object.<anonymous> (/Users/zmarouf/.nvm/versions/node/v0.12.7/lib/node_modules/vantage/examples/tour/tour.js:281:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

```
With version 1.4.0:

```
$ vantage tour
module.js:338
    throw err;
          ^
Error: Cannot find module './../../lib/util'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/zmarouf/.nvm/versions/node/v0.12.7/lib/node_modules/vantage/examples/tour/tour.js:15:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

```
With version 1.3.12
```
$ vantage tour

  ## 1. To start, press [enter] 3 times.

tour~$

```
So I looked into things a little and it seems that vorpal 1.0.3 breaks things.
Setting the dependency to 1.0.2 fixes things as far as the tour is concerned except for your hacker-news-example.
I get this:
```
use vantage-hacker-news
Installing vantage-hacker-news from the NPM registry:
runTopLevelLifecycles     ▀ ╢█████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
Error downloading module:
```
and the option is not visible in the 'help' menu.

I hope that helps with your investigations.

**Comment by dthree** [comment]
Thanks for the details.

I  found out just recently that an `inquirer` upgrade, while 1/8th the last version's size, broke some of the UI internals on Vorpal, you are correct.

Working hard to get this fixed, will let you know when it's done.

**Comment by zmarouf** [comment]
Great :) Looking forward to adding both Vorpal and Vantage to my toolbox.

**Comment by dthree** [comment]
Thanks! Happy you find them useful!

Okay - try `v1.5.1` - it seems to totally handle the problem and I tried out the tour.

On the `use` command, this was removed from the tour as I made it an extension - `vorpal-use`, which you can import if you want like this:

`vantage.use(require('vorpal-use`))`

It depends on NPM, which is pretty big, and not everyone needs it so I made it optional.

Also, check out the new `.parse` command I added to Vorpal / Vantage :)

Let me know if you're still having trouble!
