### ISSUE TITLE
How to exit from vantage?

### ISSUE THREAD

**Issue by giggioz** [dthree/vantage#73]
I tried this

vantage.exec('exit', ...)

but it does not work.

Thanks

**Comment by giggioz** [comment]
```
const Vantage = require('vantage')

const v = Vantage()
    .delimiter('$test')
    .listen(9000)
    .show()

const close = () => {
    v.exec('exit', () => {
        console.log('DONE')
    })
}
setTimeout(close, 1000)

```
i get


Error: UI Prompt called when already mid prompt.
    at Object.prompt (/Users/giggioz/Spaghetti/keeper/keeper-giochipiu-delegates/node_modules/vorpal/lib/ui.js:131:13)
    at Vorpal.vorpal.prompt (/Users/giggioz/Spaghetti/keeper/keeper-giochipiu-delegates/node_modules/vorpal/lib/vorpal.js:450:8)
    at Vorpal.vorpal.exit (/Users/giggioz/Spaghetti/keeper/keeper-giochipiu-delegates/node_modules/vorpal/lib/vorpal.js:1160:12)
    at Session.<anonymous> (/Users/giggioz/Spaghetti/keeper/keeper-giochipiu-delegates/node_modules/vorpal/lib/vorpal-commons.js:49:19)
    at Vorpal.vorpal._exec (/Users/giggioz/Spaghetti/keeper/keeper-giochipiu-delegates/node_modules/vorpal/lib/vorpal.js:846:18)
    at Vorpal.vorpal._execQueueItem (/Users/giggioz/Spaghetti/keeper/keeper-giochipiu-delegates/node_modules/vorpal/lib/vorpal.js:594:10)
    at Vorpal.vorpal._queueHandler (/Users/giggioz/Spaghetti/keeper/keeper-giochipiu-delegates/node_modules/vorpal/lib/vorpal.js:579:10)
    at Vorpal.vorpal.exec (/Users/giggioz/Spaghetti/keeper/keeper-giochipiu-delegates/node_modules/vorpal/lib/vorpal.js:554:24)
    at Timeout.close [as _onTimeout] (/Users/giggioz/Spaghetti/keeper/keeper-giochipiu-delegates/xxx.js:9:7)
    at ontimeout (timers.js:380:14)

**Comment by giggioz** [comment]
Solved this way:

```
const Vantage = require('vantage')

Vantage()
    .delimiter('$test')
    .listen(9000)
    .show()

const close = () => {
    process.exit(1)
}
setTimeout(close, 1000)
```
