### ISSUE TITLE
ReferenceError: Promise is not defined on Windows 8.1

### ISSUE THREAD

**Issue by Ridermansb** [dthree/vantage#9]
After create a simple `js`

    var Vantage = require('vantage');
    var server = new Vantage();

    server
      .command('foo')
      .description('Outputs "bar".')
      .action(function(args, cb) {
        console.log('bar');
        cb();
      });

    server
      .delimiter('webapp~$')
      .listen(80)
      .show();

And try to execute: `node .\countdownSet.js`

an error is display: 

      Error: Cannot find module 'vantage'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\ridermanb\Projects\countdownSet\countdownSet.js:1:81)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

So I try to execute a simple `vantage`, and again, a new error is display:

    ReferenceError: Promise is not defined
        at VantageClient.vantageClient.connect (C:\Program Files\nodejs\node_modules\vantage\lib\client.js:49:14)
        at Vantage.vantage.connect (C:\Program Files\nodejs\node_modules\vantage\lib\vantage.js:253:30)
        at Object.<anonymous> (C:\Program Files\nodejs\node_modules\vantage\bin\vantage.js:66:26)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)
        at node.js:906:3

> Yes, I install it using `npm install -g vantage`

**Comment by dthree** [comment]
Thanks for the feedback.

Promises are an ES6 feature, and so are only supported in the latest versions of Node and IOJS. I will be including a polyfill to increase support to earlier versions of node, but for now if you update your Node version, it should work!

**Comment by Ridermansb** [comment]
Ok Thanks. Work for me :)

**Comment by dthree** [comment]
Vantage should now work on all major Node platforms. I had since added this polyfill.
